#ifndef DATA_H
#define DATA_H

const char* names[] = {
    "Michael",
    "Christopher",
    "Jessica",
    "Matthew",
    "Ashley",
    "Jennifer",
    "Joshua",
    "Amanda",
    "Daniel",
    "David",
    "James",
    "Robert",
    "John",
    "Joseph",
    "Andrew",
    "Ryan",
    "Brandon",
    "Jason",
    "Justin",
    "Sarah",
    "William",
    "Jonathan",
    "Stephanie",
    "Brian",
    "Nicole",
    "Nicholas",
    "Anthony",
    "Heather",
    "Eric",
    "Elizabeth",
    "Adam",
    "Megan",
    "Melissa",
    "Kevin",
    "Steven",
    "Thomas",
    "Timothy",
    "Christina",
    "Kyle",
    "Rachel",
    "Laura",
    "Lauren",
    "Amber",
    "Brittany",
    "Danielle",
    "Richard",
    "Kimberly",
    "Jeffrey",
    "Amy",
    "Crystal",
    "Michelle",
    "Tiffany",
    "Jeremy",
    "Benjamin",
    "Mark",
    "Emily",
    "Aaron",
    "Charles",
    "Rebecca",
    "Jacob",
    "Stephen",
    "Patrick",
    "Sean",
    "Erin",
    "Zachary",
    "Jamie",
    "Kelly",
    "Samantha",
    "Nathan",
    "Sara",
    "Dustin",
    "Paul",
    "Angela",
    "Tyler",
    "Scott",
    "Katherine",
    "Andrea",
    "Gregory",
    "Erica",
    "Mary",
    "Travis",
    "Lisa",
    "Kenneth",
    "Bryan",
    "Lindsey",
    "Kristen",
    "Jose",
    "Alexander",
    "Jesse",
    "Katie",
    "Lindsay",
    "Shannon",
    "Vanessa",
    "Courtney",
    "Christine",
    "Alicia",
    "Cody",
    "Allison",
    "Bradley",
    "Samuel",
    "Shawn",
    "April",
    "Derek",
    "Kathryn",
    "Kristin",
    "Chad",
    "Jenna",
    "Tara",
    "Maria",
    "Krystal",
    "Jared",
    "Anna",
    "Edward",
    "Julie",
    "Peter",
    "Holly",
    "Marcus",
    "Kristina",
    "Natalie",
    "Jordan",
    "Victoria",
    "Jacqueline",
    "Corey",
    "Keith",
    "Monica",
    "Juan",
    "Donald",
    "Cassandra",
    "Meghan",
    "Joel",
    "Shane",
    "Phillip",
    "Patricia",
    "Brett",
    "Ronald",
    "Catherine",
    "George",
    "Antonio",
    "Cynthia",
    "Stacy",
    "Kathleen",
    "Raymond",
    "Carlos",
    "Brandi",
    "Douglas",
    "Nathaniel",
    "Ian",
    "Craig",
    "Brandy",
    "Alex",
    "Valerie",
    "Veronica",
    "Cory",
    "Whitney",
    "Gary",
    "Derrick",
    "Philip",
    "Luis",
    "Diana",
    "Chelsea",
    "Leslie",
    "Caitlin",
    "Leah",
    "Natasha",
    "Erika",
    "Casey",
    "Latoya",
    "Erik",
    "Dana",
    "Victor",
    "Brent",
    "Dominique",
    "Frank",
    "Brittney",
    "Evan",
    "Gabriel",
    "Julia",
    "Candice",
    "Karen",
    "Melanie",
    "Adrian",
    "Stacey",
    "Margaret",
    "Sheena",
    "Wesley",
    "Vincent",
    "Alexandra",
    "Katrina",
    "Bethany",
    "Nichole",
    "Larry",
    "Jeffery",
    "Curtis",
    "Carrie",
    "Todd",
    "Blake",
    "Christian",
    "Randy",
    "Dennis",
    "Alison",
    "Trevor",
    "Seth",
    "Kara",
    "Joanna",
    "Rachael",
    "Luke",
    "Felicia",
    "Brooke",
    "Austin",
    "Candace",
    "Jasmine",
    "Jesus",
    "Alan",
    "Susan",
    "Sandra",
    "Tracy",
    "Kayla",
    "Nancy",
    "Tina",
    "Krystle",
    "Russell",
    "Jeremiah",
    "Carl",
    "Miguel",
    "Tony",
    "Alexis",
    "Gina",
    "Jillian",
    "Pamela",
    "Mitchell",
    "Hannah",
    "Renee",
    "Denise",
    "Molly",
    "Jerry",
    "Misty",
    "Mario",
    "Johnathan",
    "Jaclyn",
    "Brenda",
    "Terry",
    "Lacey",
    "Shaun",
    "Devin",
    "Heidi",
    "Troy",
    "Lucas",
    "Desiree",
    "Jorge",
    "Andre",
    "Morgan",
    "Drew",
    "Sabrina",
    "Miranda",
    "Alyssa",
    "Alisha",
    "Teresa",
    "Johnny",
    "Meagan",
    "Allen",
    "Krista",
    "Marc",
    "Tabitha",
    "Lance",
    "Ricardo",
    "Martin",
    "Chase",
    "Theresa",
    "Melinda",
    "Monique",
    "Tanya",
    "Linda",
    "Kristopher",
    "Bobby",
    "Caleb",
    "Ashlee",
    "Kelli",
    "Henry",
    "Garrett",
    "Mallory",
    "Jill",
    "Jonathon",
    "Kristy",
    "Anne",
    "Francisco",
    "Danny",
    "Robin",
    "Lee",
    "Tamara",
    "Manuel",
    "Meredith",
    "Colleen",
    "Lawrence",
    "Christy",
    "Ricky",
    "Randall",
    "Marissa",
    "Ross",
    "Mathew",
    "Jimmy",
    "Abigail",
    "Kendra",
    "Carolyn",
    "Billy",
    "Deanna",
    "Jenny",
    "Jon",
    "Albert",
    "Taylor",
    "Lori",
    "Rebekah",
    "Cameron",
    "Ebony",
    "Wendy",
    "Angel",
    "Micheal",
    "Kristi",
    "Caroline",
    "Colin",
    "Dawn",
    "Kari",
    "Clayton",
    "Arthur",
    "Roger",
    "Roberto",
    "Priscilla",
    "Darren",
    "Kelsey",
    "Clinton",
    "Walter",
    "Louis",
    "Barbara",
    "Isaac",
    "Cassie",
    "Grant",
    "Cristina",
    "Tonya",
    "Rodney",
    "Bridget",
    "Joe",
    "Cindy",
    "Oscar",
    "Willie",
    "Maurice",
    "Jaime",
    "Angelica",
    "Sharon",
    "Julian",
    "Jack",
    "Jay",
    "Calvin",
    "Marie",
    "Hector",
    "Kate",
    "Adrienne",
    "Tasha",
    "Michele",
    "Ana",
    "Stefanie",
    "Cara",
    "Alejandro",
    "Ruben",
    "Gerald",
    "Audrey",
    "Kristine",
    "Ann",
    "Shana",
    "Javier",
    "Katelyn",
    "Brianna",
    "Bruce",
    "Deborah",
    "Claudia",
    "Carla",
    "Wayne",
    "Roy",
    "Virginia",
    "Haley",
    "Brendan",
    "Janelle",
    "Jacquelyn",
    "Beth",
    "Edwin",
    "Dylan",
    "Dominic",
    "Latasha",
    "Darrell",
    "Geoffrey",
    "Savannah",
    "Reginald",
    "Carly",
    "Fernando",
    "Ashleigh",
    "Aimee",
    "Regina",
    "Mandy",
    "Sergio",
    "Rafael",
    "Pedro",
    "Janet",
    "Kaitlin",
    "Frederick",
    "Cheryl",
    "Autumn",
    "Tyrone",
    "Martha",
    "Omar",
    "Lydia",
    "Jerome",
    "Theodore",
    "Abby",
    "Neil",
    "Shawna",
    "Sierra",
    "Nina",
    "Tammy",
    "Nikki",
    "Terrance",
    "Donna",
    "Claire",
    "Cole",
    "Trisha",
    "Bonnie",
    "Diane",
    "Summer",
    "Carmen",
    "Mayra",
    "Jermaine",
    "Eddie",
    "Micah",
    "Marvin",
    "Levi",
    "Emmanuel",
    "Brad",
    "Taryn",
    "Toni",
    "Jessie",
    "Evelyn",
    "Darryl",
    "Ronnie",
    "Joy",
    "Adriana",
    "Ruth",
    "Mindy",
    "Spencer",
    "Noah",
    "Raul",
    "Suzanne",
    "Sophia",
    "Dale",
    "Jodi",
    "Christie",
    "Raquel",
    "Naomi",
    "Kellie",
    "Ernest",
    "Jake",
    "Grace",
    "Tristan",
    "Shanna",
    "Hilary",
    "Eduardo",
    "Ivan",
    "Hillary",
    "Yolanda",
    "Alberto",
    "Andres",
    "Olivia",
    "Armando",
    "Paula",
    "Amelia",
    "Sheila",
    "Rosa",
    "Robyn",
    "Kurt",
    "Dane",
    "Glenn",
    "Nicolas",
    "Gloria",
    "Eugene",
    "Logan",
    "Steve",
    "Ramon",
    "Bryce",
    "Tommy",
    "Preston",
    "Keri",
    "Devon",
    "Alana",
    "Marisa",
    "Melody",
    "Rose",
    "Barry",
    "Marco",
    "Karl",
    "Daisy",
    "Leonard",
    "Randi",
    "Maggie",
    "Charlotte"
};

const char* surnames[] = {
    "Chung ",
    "Chen ",
    "Melton ",
    "Hill ",
    "Puckett ",
    "Song ",
    "Hamilton ",
    "Bender ",
    "Wagner ",
    "McLaughlin ",
    "McNamara ",
    "Raynor ",
    "Moon ",
    "Woodard ",
    "Desai ",
    "Wallace ",
    "Lawrence ",
    "Griffin ",
    "Dougherty ",
    "Powers ",
    "May ",
    "Steele ",
    "Teague ",
    "Vick ",
    "Gallagher ",
    "Solomon ",
    "Walsh ",
    "Monroe ",
    "Connolly ",
    "Hawkins ",
    "Middleton ",
    "Goldstein ",
    "Watts ",
    "Johnston ",
    "Weeks ",
    "Wilkerson ",
    "Barton ",
    "Walton ",
    "Hall ",
    "Ross ",
    "Woods ",
    "Mangum ",
    "Joseph ",
    "Rosenthal ",
    "Bowden ",
    "Underwood ",
    "Jones ",
    "Baker ",
    "Merritt ",
    "Cross ",
    "Cooper ",
    "Holmes ",
    "Sharpe ",
    "Morgan ",
    "Hoyle ",
    "Allen ",
    "Rich ",
    "Grant ",
    "Proctor ",
    "Diaz ",
    "Graham ",
    "Watkins ",
    "Hinton ",
    "Marsh ",
    "Hewitt ",
    "Branch ",
    "O'Brien ",
    "Case ",
    "Christensen ",
    "Parks ",
    "Hardin ",
    "Lucas ",
    "Eason ",
    "Davidson ",
    "Whitehead ",
    "Rose ",
    "Sparks ",
    "Moore ",
    "Pearson ",
    "Rodgers ",
    "Graves ",
    "Scarborough ",
    "Sutton ",
    "Sinclair ",
    "Bowman ",
    "Olsen ",
    "Love ",
    "McLean ",
    "Christian ",
    "Lamb ",
    "James ",
    "Chandler ",
    "Stout ",
    "Cowan ",
    "Golden ",
    "Bowling ",
    "Beasley ",
    "Clapp ",
    "Abrams ",
    "Tilley ",
    "Morse ",
    "Boykin ",
    "Sumner ",
    "Cassidy ",
    "Heath ",
    "Blanchard ",
    "McAllister ",
    "McKenzie ",
    "Byrne ",
    "Schroeder ",
    "Gross ",
    "Perkins ",
    "Robertson ",
    "Palmer ",
    "Brady ",
    "Rowe ",
    "Zhang ",
    "Hodge ",
    "Li ",
    "Justice ",
    "Glass ",
    "Willis ",
    "Hester ",
    "Floyd ",
    "Fischer ",
    "Norman ",
    "Chan ",
    "Hunt ",
    "Byrd ",
    "Lane ",
    "Kaplan ",
    "Heller ",
    "Jennings ",
    "Hanna ",
    "Locklear ",
    "Holloway ",
    "Glover ",
    "O'Donnell ",
    "Goldman ",
    "McKenna ",
    "Starr ",
    "Stone ",
    "McClure ",
    "Watson ",
    "Abbott ",
    "Singer ",
    "Farrell ",
    "Atkins ",
    "Sykes ",
    "Reid ",
    "Finch ",
    "Hobbs ",
    "Adkins ",
    "Kinney ",
    "Whitaker ",
    "Alexander ",
    "Conner ",
    "Waters ",
    "Becker ",
    "Rollins ",
    "Black ",
    "Fox ",
    "Hatcher ",
    "Wu ",
    "Lloyd ",
    "Joyce ",
    "Welch ",
    "Matthews ",
    "Chappell ",
    "MacDonald ",
    "Kane ",
    "Butler ",
    "Pickett ",
    "Kennedy ",
    "Thornton ",
    "McNeill ",
    "Weinstein ",
    "Moss ",
    "Carlton ",
    "Schultz ",
    "Nichols ",
    "Harvey ",
    "Stevenson ",
    "Houston ",
    "Dunn ",
    "West ",
    "Barr ",
    "Snyder ",
    "Cain ",
    "Boswell ",
    "Pittman ",
    "Weiner ",
    "Petersen ",
    "Davis ",
    "Coleman ",
    "Terrell ",
    "Burch ",
    "Parrott ",
    "Henry ",
    "Gray ",
    "Chang ",
    "Siegel ",
    "Garrett ",
    "Neal ",
    "Shaffer ",
    "Choi ",
    "Carver ",
    "Shelton ",
    "House ",
    "Lyons ",
    "Moser ",
    "Dickinson ",
    "Dodson ",
    "Spencer ",
    "Burgess ",
    "Liu ",
    "Wong ",
    "Blackburn ",
    "McKay ",
    "Frazier ",
    "Braswell ",
    "Donovan ",
    "Barrett ",
    "Nance ",
    "Washington ",
    "Rogers ",
    "McMahon ",
    "Miles ",
    "Kramer ",
    "Bowles ",
    "Brown ",
    "Bolton ",
    "Craven ",
    "Hendrix ",
    "Saunders ",
    "Lehman ",
    "Sherrill ",
    "Cash ",
    "Sullivan ",
    "Mack ",
    "Rice ",
    "Ayers ",
    "Cherry ",
    "Richmond ",
    "York ",
    "Wiley ",
    "Harrington ",
    "Reed ",
    "Nash ",
    "Kent ",
    "Holland ",
    "Clements ",
    "Hawley ",
    "Skinner ",
    "Hamrick ",
    "Winters ",
    "Dolan ",
    "Turner ",
    "Beatty ",
    "Douglas ",
    "Hendricks ",
    "Mayer ",
    "Cochran ",
    "Reilly ",
    "Jensen ",
    "Yates ",
    "Haynes ",
    "Harmon ",
    "Dawson ",
    "Barefoot ",
    "Pope ",
    "Schwartz ",
    "Singleton ",
    "Ballard ",
    "Spivey ",
    "Denton ",
    "Huff ",
    "Berger ",
    "McCall ",
    "Pollard ",
    "Garcia ",
    "Crane ",
    "Wolf ",
    "Dalton ",
    "Currin ",
    "Stanton ",
    "Carey ",
    "Hess ",
    "Robinson ",
    "Mills ",
    "McDonald ",
    "Lanier ",
    "Harris ",
    "Parsons ",
    "Vaughn ",
    "Banks ",
    "Oakley ",
    "Rubin ",
    "Maynard ",
    "Livingston",
    "Lam",
    "Thompson ",
    "Creech ",
    "Dillon ",
    "Foster ",
    "Roy ",
    "Barbour ",
    "Burke ",
    "Ritchie ",
    "Odom ",
    "Pearce ",
    "Rosenberg ",
    "O'Connor ",
    "Cates ",
    "McIntosh ",
    "Olson ",
    "Cox ",
    "Erickson ",
    "Briggs ",
    "Klein ",
    "Goldberg ",
    "Hinson ",
    "Weiss ",
    "Pritchard ",
    "Lassiter ",
    "Massey ",
    "Stark ",
    "Dunlap ",
    "Humphrey ",
    "Horowitz ",
    "Lutz ",
    "Hoover ",
    "Kang ",
    "Ellington ",
    "Lynn ",
    "Albright ",
    "Alston ",
    "Burnette ",
    "O'Neal ",
    "Morris ",
    "Callahan ",
    "Conway ",
    "Savage ",
    "Henson ",
    "Wang ",
    "Ellis ",
    "Pierce ",
    "Woodward ",
    "Godfrey ",
    "Langston ",
    "Eaton ",
    "Lowe ",
    "Fuller ",
    "Simmons ",
    "Knight ",
    "Gold ",
    "Hensley ",
    "French ",
    "Hughes ",
    "Pate ",
    "Burnett ",
    "Francis ",
    "Horn ",
    "Forrest ",
    "Levin ",
    "Durham ",
    "Guthrie ",
    "Freedman ",
    "Wiggins ",
    "Best ",
    "Crawford ",
    "Drake ",
    "Curtis ",
    "Walter ",
    "Jenkins ",
    "Hood ",
    "Jiang ",
    "Johnson ",
    "Craig ",
    "McIntyre ",
    "Brantley ",
    "Kelley ",
    "Smith ",
    "Wall ",
    "Quinn ",
    "Hicks ",
    "Garrison ",
    "Dickerson ",
    "Waller ",
    "Carter ",
    "Katz ",
    "Hull ",
    "Brock ",
    "McMillan ",
    "Hu ",
    "McKee ",
    "Sims ",
    "Henderson ",
    "Rao ",
    "Bray ",
    "Ford ",
    "Blum ",
    "Kenney ",
    "Gordon ",
    "Blair ",
    "Kemp ",
    "Hutchinson ",
    "Brennan ",
    "Little ",
    "Gill ",
    "Keller ",
    "McConnell ",
    "Sawyer ",
    "Coates ",
    "Lindsay ",
    "Gonzalez ",
    "English ",
    "Duke ",
    "Webb ",
    "Baldwin ",
    "Fletcher ",
    "Boyd ",
    "Hirsch ",
    "Currie ",
    "Weber ",
    "Honeycutt ",
    "Manning ",
    "Riley ",
    "Swanson ",
    "Huffman ",
    "Gibson ",
    "Wrenn ",
    "Green ",
    "Hayes ",
    "Koch ",
    "Harrell ",
    "McGuire ",
    "Stephenson ",
    "Baxter ",
    "Summers ",
    "Nixon ",
    "Kelly ",
    "Cobb ",
    "Bruce ",
    "Newton ",
    "Sanchez ",
    "Silverman ",
    "Richardson ",
    "Gay ",
    "Chase ",
    "Kern ",
    "Scott ",
    "Bradley ",
    "Yang ",
    "Bunn ",
    "Link ",
    "Nguyen ",
    "Stephens ",
    "Horne ",
    "Burton ",
    "Berry ",
    "Knowles ",
    "Freeman ",
    "Hernandez ",
    "Roach ",
    "Hardison ",
    "Caldwell ",
    "Mann ",
    "McLeod ",
    "Park ",
    "Phillips ",
    "Pitts ",
    "Gould ",
    "Shapiro ",
    "Vincent ",
    "Fisher ",
    "McPherson ",
    "McFarland ",
    "Holden ",
    "Hartman ",
    "Friedman ",
    "Adcock ",
    "Lang ",
    "Aldridge ",
    "Davies ",
    "Ferrell ",
    "Hedrick ",
    "Singh ",
    "Blalock ",
    "Grossman ",
    "Pugh ",
    "Fernandez ",
    "Arnold ",
    "Stanley ",
    "Field",
    "Farmer",
    "Jernigan",
    "Bowers",
    "Crabtree",
    "Archer"
};

const char* cities[] = {
    "Aberdeen",
    "Abilene",
    "Akron",
    "Albany",
    "Albuquerque",
    "Alexandria",
    "Allentown",
    "Amarillo",
    "Anaheim",
    "Anchorage",
    "Ann Arbor",
    "Antioch",
    "Apple Valley",
    "Appleton",
    "Arlington",
    "Arvada",
    "Asheville",
    "Athens",
    "Atlanta",
    "Atlantic City",
    "Augusta",
    "Aurora",
    "Austin",
    "Bakersfield",
    "Baltimore",
    "Barnstable",
    "Baton Rouge",
    "Beaumont",
    "Bel Air",
    "Bellevue",
    "Berkeley",
    "Bethlehem",
    "Billings",
    "Birmingham",
    "Bloomington",
    "Boise",
    "Boise City",
    "Bonita Springs",
    "Boston",
    "Boulder",
    "Bradenton",
    "Bremerton",
    "Bridgeport",
    "Brighton",
    "Brownsville",
    "Bryan",
    "Buffalo",
    "Burbank",
    "Burlington",
    "Cambridge",
    "Canton",
    "Cape Coral",
    "Carrollton",
    "Cary",
    "Cathedral City",
    "Cedar Rapids",
    "Champaign",
    "Chandler",
    "Charleston",
    "Charlotte",
    "Chattanooga",
    "Chesapeake",
    "Chicago",
    "Chula Vista",
    "Cincinnati",
    "Clarke County",
    "Clarksville",
    "Clearwater",
    "Cleveland",
    "College Station",
    "Colorado Springs",
    "Columbia",
    "Columbus",
    "Concord",
    "Coral Springs",
    "Corona",
    "Corpus Christi",
    "Costa Mesa",
    "Dallas",
    "Daly City",
    "Danbury",
    "Davenport",
    "Davidson County",
    "Dayton",
    "Daytona Beach",
    "Deltona",
    "Denton",
    "Denver",
    "Des Moines",
    "Detroit",
    "Downey",
    "Duluth",
    "Durham",
    "El Monte",
    "El Paso",
    "Elizabeth",
    "Elk Grove",
    "Elkhart",
    "Erie",
    "Escondido",
    "Eugene",
    "Evansville",
    "Fairfield",
    "Fargo",
    "Fayetteville",
    "Fitchburg",
    "Flint",
    "Fontana",
    "Fort Collins",
    "Fort Lauderdale",
    "Fort Smith",
    "Fort Walton Beach",
    "Fort Wayne",
    "Fort Worth",
    "Frederick",
    "Fremont",
    "Fresno",
    "Fullerton",
    "Gainesville",
    "Garden Grove",
    "Garland",
    "Gastonia",
    "Gilbert",
    "Glendale",
    "Grand Prairie",
    "Grand Rapids",
    "Grayslake",
    "Green Bay",
    "GreenBay",
    "Greensboro",
    "Greenville",
    "Gulfport-Biloxi",
    "Hagerstown",
    "Hampton",
    "Harlingen",
    "Harrisburg",
    "Hartford",
    "Havre de Grace",
    "Hayward",
    "Hemet",
    "Henderson",
    "Hesperia",
    "Hialeah",
    "Hickory",
    "High Point",
    "Hollywood",
    "Honolulu",
    "Houma",
    "Houston",
    "Howell",
    "Huntington",
    "Huntington Beach",
    "Huntsville",
    "Independence",
    "Indianapolis",
    "Inglewood",
    "Irvine",
    "Irving",
    "Jackson",
    "Jacksonville",
    "Jefferson",
    "Jersey City",
    "Johnson City",
    "Joliet",
    "Kailua",
    "Kalamazoo",
    "Kaneohe",
    "Kansas City",
    "Kennewick",
    "Kenosha",
    "Killeen",
    "Kissimmee",
    "Knoxville",
    "Lacey",
    "Lafayette",
    "Lake Charles",
    "Lakeland",
    "Lakewood",
    "Lancaster",
    "Lansing",
    "Laredo",
    "Las Cruces",
    "Las Vegas",
    "Layton",
    "Leominster",
    "Lewisville",
    "Lexington",
    "Lincoln",
    "Little Rock",
    "Long Beach",
    "Lorain",
    "Los Angeles",
    "Louisville",
    "Lowell",
    "Lubbock",
    "Macon",
    "Madison",
    "Manchester",
    "Marina",
    "Marysville",
    "McAllen",
    "McHenry",
    "Medford",
    "Melbourne",
    "Memphis",
    "Merced",
    "Mesa",
    "Mesquite",
    "Miami",
    "Milwaukee",
    "Minneapolis",
    "Miramar",
    "Mission Viejo",
    "Mobile",
    "Modesto",
    "Monroe",
    "Monterey",
    "Montgomery",
    "Moreno Valley",
    "Murfreesboro",
    "Murrieta",
    "Muskegon",
    "Myrtle Beach",
    "Naperville",
    "Naples",
    "Nashua",
    "Nashville",
    "New Bedford",
    "New Haven",
    "New London",
    "New Orleans",
    "New York",
    "New York City",
    "Newark",
    "Newburgh",
    "Newport News",
    "Norfolk",
    "Normal",
    "Norman",
    "North Charleston",
    "North Las Vegas",
    "North Port",
    "Norwalk",
    "Norwich",
    "Oakland",
    "Ocala",
    "Oceanside",
    "Odessa",
    "Ogden",
    "Oklahoma City",
    "Olathe",
    "Olympia",
    "Omaha",
    "Ontario",
    "Orange",
    "Orem",
    "Orlando",
    "Overland Park",
    "Oxnard",
    "Palm Bay",
    "Palm Springs",
    "Palmdale",
    "Panama City",
    "Pasadena",
    "Paterson",
    "Pembroke Pines",
    "Pensacola",
    "Peoria",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Plano",
    "Pomona",
    "Pompano Beach",
    "Port Arthur",
    "Port Orange",
    "Port Saint Lucie",
    "Port St. Lucie",
    "Portland",
    "Portsmouth",
    "Poughkeepsie",
    "Providence",
    "Provo",
    "Pueblo",
    "Punta Gorda",
    "Racine",
    "Raleigh",
    "Rancho Cucamonga",
    "Reading",
    "Redding",
    "Reno",
    "Richland",
    "Richmond",
    "Richmond County",
    "Riverside",
    "Roanoke",
    "Rochester",
    "Rockford",
    "Worcester",
    "Yakima"
};

// const char* names[] = {
//   "Yannis",
//   "Christofos",
//   "Sofia",
//   "Marianna",
//   "Vagelis",
//   "Maria",
//   "Iosif",
//   "Dionisis",
//   "Konstantina",
//   "Theofilos",
//   "Giorgos",
//   "Dimitris"
// };

// const char* surnames[] = {
//   "Ioannidis",
//   "Svingos",
//   "Karvounari",
//   "Rezkalla",
//   "Nikolopoulos",
//   "Berreta",
//   "Koronis",
//   "Gaitanis",
//   "Oikonomou",
//   "Mailis",
//   "Michas",
//   "Halatsis"
// };

// const char* cities[] = {
//   "Athens",
//   "San Francisco",
//   "Los Angeles",
//   "Amsterdam",
//   "London",
//   "New York",
//   "Tokyo",
//   "Hong Kong",
//   "Munich",
//   "Miami"
// };

#endif // DATA_H